// <auto-generated />
using AlrightBooks.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AlrightBooks.Migrations
{
    [DbContext(typeof(AlrightBooksContext))]
    [Migration("20171009232616_Intial")]
    partial class Intial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlrightBooks.Models.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("AdvRating");

                    b.Property<string>("Author");

                    b.Property<int?>("BookListID");

                    b.Property<string>("ImgURL");

                    b.Property<string>("Title");

                    b.HasKey("BookID");

                    b.HasIndex("BookListID");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("AlrightBooks.Models.BookList", b =>
                {
                    b.Property<int>("BookListID")
                        .ValueGeneratedOnAdd();

                    b.HasKey("BookListID");

                    b.ToTable("BookList");
                });

            modelBuilder.Entity("AlrightBooks.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BookListID");

                    b.Property<string>("FaveGenre");

                    b.Property<string>("Name");

                    b.HasKey("UserID");

                    b.HasIndex("BookListID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("AlrightBooks.Models.Book", b =>
                {
                    b.HasOne("AlrightBooks.Models.BookList", "BookList")
                        .WithMany("Books")
                        .HasForeignKey("BookListID");
                });

            modelBuilder.Entity("AlrightBooks.Models.User", b =>
                {
                    b.HasOne("AlrightBooks.Models.BookList", "BookList")
                        .WithMany("Users")
                        .HasForeignKey("BookListID");
                });
#pragma warning restore 612, 618
        }
    }
}
